export type Feature = { id:string; name:string; category:string; points:number; tags:string[] };
export type SchemaField = { name:string; type:string; required:boolean };
export type SchemaTable = { name:string; fields:SchemaField[] };
export type ApiRoute = { method:'GET'|'POST'|'PUT'|'PATCH'|'DELETE'; path:string; purpose:string; auth:boolean };

export const FEATURES: Feature[] = [
  ...['Authentication','Email verification','Password reset','Role based access','Admin dashboard','User dashboard','Profile management','Notifications','Search','Filtering','Pagination','Favorites','Reviews','Ratings','File upload','Image processing','Audit logs','Analytics','Feature flags','Webhooks','Background jobs','Email delivery','CSV import','CSV export','PDF export','DOCX export','Markdown export','JSON export','Dark mode','Localization','Accessibility','SEO','PWA','Offline cache','Rate limiting','API versioning','OpenAPI docs','Health checks','Structured logging','Error tracking','Metrics','Caching','Queue processing','Object storage','CDN','Full text search','Recommendations','Cart','Checkout','Orders','Payments','Coupons','Inventory','Product catalog','Variants','Tax calculation','Shipping','Returns','Wishlists','Subscriptions','Invoices','Refunds','Fraud checks','Idempotency','Stock reservations','Seller portal','Customer support','Chat','Content moderation','Data retention','Backups','Disaster recovery','Consent management','Cookie controls','Two factor auth','Session management','Device management','Data export','Account deletion'].map((name,i)=>({id:`f-${i+1}`,name,category:'Core',points:2+(i%6),tags:[]})),
];

const ECOMMERCE_NAMES = ['Product catalog','Variants','Search','Filtering','Pagination','Cart','Checkout','Orders','Payments','Coupons','Inventory','Tax calculation','Shipping','Returns','Wishlists','Reviews','Ratings','Subscriptions','Invoices','Refunds','Fraud checks','Idempotency','Stock reservations','Email delivery','Notifications','Admin dashboard','User dashboard','Role based access','Audit logs','Analytics','Webhooks','Background jobs','Caching','CDN','Object storage','Image processing','Rate limiting','API versioning','OpenAPI docs','Health checks','Structured logging','Error tracking','Metrics','Full text search','Localization','SEO','PWA','Accessibility','Data export','Account deletion','Consent management','Cookie controls','Two factor auth','Session management','Device management','Backups','Disaster recovery','Data retention'];

const table = (name:string, fields:string[]):SchemaTable=>({name,fields:fields.map((f,i)=>({name:f,type:f==='id'||f.endsWith('_id')?'uuid':f.includes('at')?'timestamp':f.includes('price')||f.includes('amount')?'decimal':'text',required:i<2}))});
export const ECOMMERCE_TABLES: SchemaTable[] = [
 table('users',['id','email','name','role','created_at','updated_at']),table('products',['id','seller_id','name','description','price','status','created_at']),table('product_variants',['id','product_id','sku','price','inventory','created_at']),table('categories',['id','name','slug','created_at']),table('product_categories',['id','product_id','category_id']),table('carts',['id','user_id','created_at','updated_at']),table('cart_items',['id','cart_id','product_id','variant_id','quantity']),table('orders',['id','user_id','status','amount','created_at','updated_at']),table('order_items',['id','order_id','product_id','variant_id','quantity','price']),table('payments',['id','order_id','provider','status','amount','created_at']),table('coupons',['id','code','discount','status','expires_at']),table('coupon_redemptions',['id','coupon_id','user_id','order_id','created_at']),table('inventory_reservations',['id','variant_id','order_id','quantity','expires_at']),table('shipments',['id','order_id','carrier','tracking','status','created_at']),table('returns',['id','order_id','reason','status','created_at']),table('reviews',['id','user_id','product_id','rating','body','created_at']),table('wishlists',['id','user_id','product_id','created_at']),table('invoices',['id','order_id','number','amount','status','created_at']),table('webhook_events',['id','provider','event_id','status','created_at']),table('audit_logs',['id','user_id','action','entity','created_at']),
];

export const ECOMMERCE_ROUTES: ApiRoute[] = [
 ['GET','/api/products','List products',false],['GET','/api/products/:id','Get product',false],['POST','/api/products','Create product',true],['PATCH','/api/products/:id','Update product',true],['DELETE','/api/products/:id','Delete product',true],['GET','/api/categories','List categories',false],['GET','/api/search','Search catalog',false],['POST','/api/cart/items','Add cart item',true],['PATCH','/api/cart/items/:id','Update cart item',true],['DELETE','/api/cart/items/:id','Remove cart item',true],['POST','/api/checkout','Create checkout',true],['POST','/api/payments/webhook','Payment webhook',false],['GET','/api/orders','List orders',true],['GET','/api/orders/:id','Get order',true],['POST','/api/orders/:id/cancel','Cancel order',true],['POST','/api/coupons/validate','Validate coupon',true],['POST','/api/reviews','Create review',true],['GET','/api/products/:id/reviews','List reviews',false],['POST','/api/wishlist/items','Add wishlist item',true],['DELETE','/api/wishlist/items/:id','Remove wishlist item',true],['GET','/api/admin/analytics','Admin analytics',true],['POST','/api/admin/inventory/adjust','Adjust inventory',true],['POST','/api/admin/refunds','Issue refund',true],['POST','/api/webhooks/:provider','Receive provider webhook',false],['GET','/api/health','Health check',false],
].map(([method,path,purpose,auth])=>({method:method as ApiRoute['method'],path,purpose,auth}));

export function routeDomain(domain:string){
  const d=domain.toLowerCase();
  if(d.includes('ecommerce')||d.includes('commerce')||d.includes('shop')||d.includes('store')) return {features:ECOMMERCE_NAMES, tables:ECOMMERCE_TABLES, routes:ECOMMERCE_ROUTES};
  if(d.includes('saas')) return {features:['Authentication','Role based access','Admin dashboard','User dashboard','Subscriptions','Invoices','Notifications','Analytics','Audit logs','API versioning','Webhooks','Background jobs','Rate limiting','Caching','Search','Data export','Account deletion','Two factor auth'],tables:[table('users',['id','email','role','created_at']),table('organizations',['id','name','created_at']),table('memberships',['id','organization_id','user_id','role']),table('subscriptions',['id','organization_id','status','created_at'])],routes:[{method:'GET',path:'/api/me',purpose:'Current user',auth:true},{method:'GET',path:'/api/organizations',purpose:'List organizations',auth:true},{method:'POST',path:'/api/organizations',purpose:'Create organization',auth:true},{method:'POST',path:'/api/billing/webhook',purpose:'Billing webhook',auth:false}]};
  if(d.includes('marketplace')) return {features:['Authentication','Role based access','Seller portal','Product catalog','Search','Filtering','Cart','Checkout','Orders','Payments','Reviews','Ratings','Notifications','Admin dashboard','Analytics','Webhooks','Fraud checks','Audit logs'],tables:ECOMMERCE_TABLES.slice(0,12),routes:ECOMMERCE_ROUTES.slice(0,18)};
  return {features:[],tables:[],routes:[]};
}

export function mergeRouting(domain:string, currentFeatures:string[], currentTables:SchemaTable[], currentRoutes:ApiRoute[]){
 const r=routeDomain(domain); const featureSet=new Set(currentFeatures); r.features.forEach(x=>featureSet.add(x)); const tableMap=new Map(currentTables.map(x=>[x.name,x])); r.tables.forEach(x=>tableMap.set(x.name,x)); const routeMap=new Map(currentRoutes.map(x=>[`${x.method} ${x.path}`,x])); r.routes.forEach(x=>routeMap.set(`${x.method} ${x.path}`,x)); return {features:[...featureSet],tables:[...tableMap.values()],routes:[...routeMap.values()]};
}

export function estimate(points:number, teamSkills:number, customRisk:number){
 const adjusted=Math.max(0,points)*(1+customRisk/100); const team=Math.max(1,Math.min(12,Math.ceil(Math.sqrt(adjusted/18)*teamSkills))); const personWeeks=Math.max(1,Math.ceil(adjusted/8)); const weeks=Math.max(1,Math.ceil(personWeeks/team)); const low=Math.round(personWeeks*team*900); const high=Math.round(personWeeks*team*1800); return {points:Math.round(adjusted),weeks,team,low,high};
}

export function featurePoints(selected:string[], extraPoints:number){return selected.reduce((sum,name)=>sum+(FEATURES.find(f=>f.name===name)?.points||3),0)+Math.max(0,extraPoints);}
