import {create} from 'zustand';
import {estimate,featurePoints,mergeRouting, type ApiRoute,type SchemaTable} from './engine';

export const STEPS=['Executive Summary','Business Context','Target Audience','Problem & Jobs','Goals & KPIs','Scope & Priorities','Features & Rules','UX & Accessibility','Platform & Tech Stack','Architecture','Database Schema','API Endpoint Planner','Integrations','Security Standards','Observability','Performance & Reliability','QA & Acceptance','Delivery Plan','Risks & Assumptions','Review & Publish'];
export type Branding={primary:string;secondary:string;logo:string;fontScale:number;density:'compact'|'comfortable'|'spacious';showCover:boolean;showToc:boolean;showEstimates:boolean};
export type ArchNode={id:string;type:'input'|'default'|'output';position:{x:number;y:number};data:{label:string;kind:string}};
export type ArchEdge={id:string;source:string;target:string};
export type PRDState={
 step:number;product:string;summary:string;business:string;audience:string;problem:string;jobs:string;goals:string;scope:string;features:string[];featureNotes:string;ux:string;platform:string;techStack:string[];architectureNotes:string;schema:SchemaTable[];routes:ApiRoute[];integrations:string[];security:string[];observability:string[];performance:string[];qa:string;delivery:string;risks:string;assumptions:string;archNodes:ArchNode[];archEdges:ArchEdge[];branding:Branding;extraPoints:number;riskPercent:number;teamSkill:number;
 set:(patch:Partial<PRDState>)=>void; next:()=>void; prev:()=>void; applyDomainRouting:(domain:string)=>void; toggleFeature:(name:string)=>void; addTable:()=>void; addRoute:()=>void; reset:()=>void;
 estimate:()=>ReturnType<typeof estimate>;
};

const defaults:Omit<PRDState,'set'|'next'|'prev'|'applyDomainRouting'|'toggleFeature'|'addTable'|'addRoute'|'reset'|'estimate'>={step:0,product:'',summary:'',business:'',audience:'',problem:'',jobs:'',goals:'',scope:'',features:[],featureNotes:'',ux:'',platform:'Web',techStack:['Next.js','TypeScript','Tailwind CSS'],architectureNotes:'',schema:[],routes:[],integrations:[],security:['HTTPS','Input validation','Authentication','Authorization','Rate limiting','Audit logging'],observability:['Structured logs','Error tracking','Health checks','Metrics'],performance:['CDN','Lazy loading','Pagination','Caching'],qa:'',delivery:'',risks:'',assumptions:'',archNodes:[{id:'n1',type:'input',position:{x:20,y:120},data:{label:'Web Client',kind:'Frontend'}},{id:'n2',type:'default',position:{x:260,y:120},data:{label:'Application',kind:'Backend'}},{id:'n3',type:'output',position:{x:500,y:120},data:{label:'Database',kind:'DB'}}],archEdges:[{id:'e1',source:'n1',target:'n2'},{id:'e2',source:'n2',target:'n3'}],branding:{primary:'#8b7cff',secondary:'#5eead4',logo:'',fontScale:1,density:'comfortable',showCover:true,showToc:true,showEstimates:true},extraPoints:0,riskPercent:15,teamSkill:1};

export const usePRD=create<PRDState>((set,get)=>({...(defaults as any),set:(patch)=>set(patch),next:()=>set(s=>({step:Math.min(STEPS.length-1,s.step+1)})),prev:()=>set(s=>({step:Math.max(0,s.step-1)})),applyDomainRouting:(domain)=>{const r=mergeRouting(domain,get().features,get().schema,get().routes);set({features:r.features,schema:r.tables,routes:r.routes,product:get().product||domain,summary:get().summary||`Deterministic product specification for ${domain}.`});},toggleFeature:(name)=>set(s=>({features:s.features.includes(name)?s.features.filter(x=>x!==name):[...s.features,name]})),addTable:()=>set(s=>({schema:[...s.schema,{name:`table_${s.schema.length+1}`,fields:[{name:'id',type:'uuid',required:true},{name:'created_at',type:'timestamp',required:true}]}]})),addRoute:()=>set(s=>({routes:[...s.routes,{method:'GET',path:`/api/resource-${s.routes.length+1}`,purpose:'Deterministic resource operation',auth:true}]})),reset:()=>set(defaults as any),estimate:()=>estimate(featurePoints(get().features,get().extraPoints)+get().schema.length*3+get().routes.length*2+get().integrations.length*2,get().teamSkill,get().riskPercent)}));

export {defaults};
