import type { VercelRequest, VercelResponse } from '@vercel/node';

type Provider = 'gemini' | 'openrouter' | 'openai' | 'anthropic' | 'groq' | 'mistral' | 'custom';
type ReqBody = { provider?: Provider; model?: string; prompt?: string; apiKey?: string; baseUrl?: string; test?: boolean };
const PROVIDERS = new Set<Provider>(['gemini','openrouter','openai','anthropic','groq','mistral','custom']);
const MAX_PROMPT_CHARS=120_000, MAX_BODY_BYTES=900_000, RATE_WINDOW_MS=60_000, RATE_LIMIT=24;
const RETRYABLE=new Set([401,403,408,409,425,429,500,502,503,504]);
const rate=new Map<string,{start:number;count:number}>();
function envKeys(provider:Provider){const prefix=provider==='custom'?'CUSTOM':provider.toUpperCase();return[process.env[`${prefix}_API_KEY`]||'',...(process.env[`${prefix}_API_KEYS`]||'').split(',')].map(x=>x.trim()).filter(Boolean);}
function clientIp(req:VercelRequest){const x=req.headers['x-forwarded-for'];return(typeof x==='string'?x.split(',')[0]:'')||req.socket?.remoteAddress||'unknown';}
function withinRateLimit(req:VercelRequest){const key=clientIp(req),now=Date.now(),old=rate.get(key);if(!old||now-old.start>=RATE_WINDOW_MS){rate.set(key,{start:now,count:1});return true;}old.count+=1;return old.count<=RATE_LIMIT;}
function isByok(req:VercelRequest){const body=(req.body||{}) as ReqBody;return typeof body.apiKey==='string'&&body.apiKey.trim().length>0;}
function configuredOrigins(){return(process.env.PRD_FORGE_ALLOWED_ORIGINS||'').split(',').map(x=>x.trim()).filter(Boolean);}
function originAllowed(req:VercelRequest){if(isByok(req))return true;const origin=typeof req.headers.origin==='string'?req.headers.origin:'';if(!origin)return false;const configured=configuredOrigins();if(configured.length)return configured.includes(origin);const host=req.headers.host||'';return origin===`https://${host}`||origin===`http://${host}`||origin==='http://localhost:3000';}
function cors(req:VercelRequest,res:VercelResponse){const origin=typeof req.headers.origin==='string'?req.headers.origin:'';const configured=configuredOrigins();const preflightAllowed=!!origin&&(configured.includes(origin)||origin.endsWith('.github.io')||origin==='http://localhost:3000');if(origin&&(isByok(req)||preflightAllowed)){res.setHeader('Access-Control-Allow-Origin',origin);res.setHeader('Vary','Origin');res.setHeader('Access-Control-Allow-Headers','Content-Type');res.setHeader('Access-Control-Allow-Methods','POST, OPTIONS');}}
function json(res:VercelResponse,status:number,payload:unknown){return res.status(status).json(payload);}
function safeBaseUrl(provider:Provider,input?:string){const defaults:Record<Provider,string>={gemini:'https://generativelanguage.googleapis.com',openrouter:'https://openrouter.ai/api',openai:'https://api.openai.com/v1',anthropic:'https://api.anthropic.com',groq:'https://api.groq.com/openai/v1',mistral:'https://api.mistral.ai/v1',custom:''};const value=(input||defaults[provider]).trim().replace(/\/$/,'');if(!value.startsWith('https://')&&!value.startsWith('http://localhost'))throw new Error('Provider endpoint must use HTTPS.');if(provider==='custom'){const allowed=(process.env.PRD_FORGE_CUSTOM_DOMAINS||'').split(',').map(x=>x.trim().toLowerCase()).filter(Boolean);let host='';try{host=new URL(value).hostname.toLowerCase();}catch{throw new Error('Invalid custom endpoint URL.');}if(!allowed.length||!allowed.includes(host))throw new Error('Custom endpoints are locked. Add the domain to PRD_FORGE_CUSTOM_DOMAINS on Vercel.');}return value;}
function headersFor(provider:Provider,key:string): Record<string,string>{const common:Record<string,string>={'Content-Type':'application/json'};if(provider==='gemini')return{...common,'x-goog-api-key':key};if(provider==='anthropic')return{...common,'x-api-key':key,'anthropic-version':'2023-06-01'};return{...common,Authorization:`Bearer ${key}`};}
function modelsRequest(provider:Provider,baseUrl:string){if(provider==='gemini')return{url:`${baseUrl}/v1beta/models`,method:'GET'};return{url:`${baseUrl}/models`,method:'GET'};}
function classifyHealth(status:number,modelAvailable:boolean){if(status>=200&&status<300)return modelAvailable?'valid-model':'valid-key-model-unavailable';if(status===401||status===403)return'invalid-or-restricted-key';if(status===404)return'model-endpoint-not-found';if(status===429)return'rate-limited-or-quota';if(status===400)return'provider-rejected-request';return`provider-error-${status}`;}
async function checkKey(provider:Provider,key:string,model:string,baseUrl:string){const spec=modelsRequest(provider,baseUrl),controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),20_000);try{const upstream=await fetch(spec.url,{method:spec.method,headers:headersFor(provider,key),cache:'no-store',signal:controller.signal});const raw=await upstream.text().catch(()=> '');let parsed:any=null;try{parsed=JSON.parse(raw);}catch{}if(!upstream.ok)return{ok:false,status:upstream.status,health:classifyHealth(upstream.status,false),modelAvailable:false,detail:extractProviderDetail(parsed,raw)};const ids=Array.isArray(parsed?.data)?parsed.data.map((x:any)=>String(x?.id||'')).filter(Boolean):Array.isArray(parsed?.models)?parsed.models.map((x:any)=>String(x?.name||'').replace(/^models\//,'')).filter(Boolean):[];const normalizedModel=model.replace(/^models\//,'');const modelAvailable=!normalizedModel||ids.includes(normalizedModel)||ids.includes(`models/${normalizedModel}`);return{ok:modelAvailable,status:modelAvailable?upstream.status:404,health:classifyHealth(modelAvailable?upstream.status:404,modelAvailable),modelAvailable,models:ids.slice(0,60),detail:modelAvailable?'':'Selected model is not available for this API key/provider endpoint.'};}catch(e){return{ok:false,status:504,health:'network-or-timeout',modelAvailable:false,detail:e instanceof Error?e.message:'Provider health check failed'};}finally{clearTimeout(timeout);}}
function extractProviderDetail(parsed:any,raw:string){return String(parsed?.error?.message||parsed?.message||raw||'Provider rejected the request').replace(/\s+/g,' ').slice(0,500);}
function requestFor(provider:Provider,model:string,prompt:string,baseUrl:string){if(provider==='gemini')return{url:`${baseUrl}/v1beta/models/${encodeURIComponent(model)}:streamGenerateContent?alt=sse`,body:{contents:[{role:'user',parts:[{text:prompt}]}],generationConfig:{temperature:.25,topP:.9,maxOutputTokens:32000}}};if(provider==='anthropic')return{url:`${baseUrl}/v1/messages`,body:{model,max_tokens:32000,temperature:.25,stream:true,messages:[{role:'user',content:prompt}]}};return{url:`${baseUrl}/chat/completions`,body:{model,temperature:.25,top_p:.9,max_tokens:32000,stream:true,messages:[{role:'user',content:prompt}]}};}
function textFromEvent(provider:Provider,data:string){try{const j=JSON.parse(data);if(provider==='gemini')return j?.candidates?.[0]?.content?.parts?.map((p:{text?:string})=>p.text||'').join('')||'';if(provider==='anthropic')return j?.type==='content_block_delta'?j?.delta?.text||'':'';return j?.choices?.[0]?.delta?.content||'';}catch{return '';}}
async function streamNormalized(res:VercelResponse,upstream:Response,provider:Provider){if(!upstream.body)throw new Error('Upstream streaming is unavailable.');res.status(200);res.setHeader('Content-Type','text/event-stream; charset=utf-8');res.setHeader('Cache-Control','no-cache, no-transform');res.setHeader('Connection','keep-alive');res.setHeader('X-Content-Type-Options','nosniff');const reader=upstream.body.getReader(),decoder=new TextDecoder();let buffer='';const send=(text:string)=>{if(text)res.write(`data: ${JSON.stringify({text})}\n\n`);};while(true){const{value,done}=await reader.read();buffer+=decoder.decode(value||new Uint8Array(),{stream:!done});const events=buffer.split(/\n\n|\r\n\r\n/);buffer=events.pop()||'';for(const event of events)for(const line of event.split(/\r?\n/)){if(!line.startsWith('data:'))continue;const data=line.slice(5).trim();if(!data||data==='[DONE]')continue;send(textFromEvent(provider,data));}if(done)break;}if(buffer.trim())for(const line of buffer.split(/\r?\n/)){if(!line.startsWith('data:'))continue;const data=line.slice(5).trim();if(data&&data!=='[DONE]')send(textFromEvent(provider,data));}res.write('data: [DONE]\n\n');res.end();}
export default async function handler(req:VercelRequest,res:VercelResponse){cors(req,res);if(req.method==='OPTIONS')return res.status(204).end();if(req.method!=='POST'){res.setHeader('Allow','POST, OPTIONS');return json(res,405,{error:'Method not allowed.'});}if(!originAllowed(req))return json(res,403,{error:'Origin not allowed.'});if(!withinRateLimit(req))return json(res,429,{error:'Rate limit reached. Try again in a minute.'});try{const rawLength=Number(req.headers['content-length']||0);if(rawLength>MAX_BODY_BYTES)return json(res,413,{error:'Request body is too large.'});const body=(req.body||{}) as ReqBody;const provider=PROVIDERS.has(body.provider as Provider)?body.provider as Provider:'gemini';const model=typeof body.model==='string'&&body.model.trim()?body.model.trim():provider==='gemini'?'gemini-2.5-flash':provider==='openrouter'?'openrouter/free':'gpt-4o-mini';const prompt=typeof body.prompt==='string'?body.prompt.trim():'';if(!prompt&&!body.test)return json(res,400,{error:'Prompt is required.'});if(prompt.length>MAX_PROMPT_CHARS)return json(res,413,{error:'Prompt is too large.'});const suppliedKey=typeof body.apiKey==='string'?body.apiKey.trim():'';const keys=suppliedKey?[suppliedKey]:envKeys(provider);if(!keys.length)return json(res,400,{error:`No ${provider} API key configured.`});const baseUrl=safeBaseUrl(provider,body.baseUrl);if(body.test){let lastHealth:any={ok:false,status:500,health:'no-working-key',modelAvailable:false};for(const key of keys){const health=await checkKey(provider,key,model,baseUrl);if(health.ok)return json(res,200,{...health,provider,model,checkedKeys:keys.length,message:`Key verified and model ${model} is available.`});lastHealth=health;}return json(res,lastHealth.status||502,{...lastHealth,provider,model,checkedKeys:keys.length,message:lastHealth.health==='valid-key-model-unavailable'?`API key is valid, but model ${model} is not available. Choose one of the returned models.`:'Key check failed. The key may be invalid/restricted, rate-limited, or the endpoint may be unavailable.'});}
let lastStatus=502,lastDetail='';for(const key of keys){const spec=requestFor(provider,model,prompt,baseUrl),controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),90_000);try{const upstream=await fetch(spec.url,{method:'POST',headers:headersFor(provider,key),body:JSON.stringify(spec.body),cache:'no-store',signal:controller.signal});if(upstream.ok&&upstream.body){clearTimeout(timeout);return await streamNormalized(res,upstream,provider);}lastStatus=upstream.status;lastDetail=extractProviderDetail(await upstream.json().catch(()=>null),'');if(!RETRYABLE.has(lastStatus))break;}catch(e){lastStatus=504;lastDetail=e instanceof Error?e.message:'Upstream request failed';}finally{clearTimeout(timeout);}}return json(res,lastStatus,{error:`${provider} request failed (${lastStatus}).`,detail:lastDetail});}catch(error){console.error('PRD Forge provider error',error);return json(res,500,{error:error instanceof Error?error.message:'Unable to process request.'});}}
